site_name: haokee-wiki
site_author: 好渴鹅

nav:
  - 开始: index.md
  - 进入 OI 的海洋:
    - 配置环境: Configure.md
    - 第一个程序: FirstProgram.md
  - 图论:
    - 最短路径:
      - Johnson全源最短路: Johnson.md
      - 差分约束: System of Difference Constraints.md
  - 树论:
    - 最近公共祖先 LCA: LCA.md
  - 站点信息:
    - 关于作者及站点: about.md

theme:
  name: 'material'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js